spring.application.name=api-gateway

server.port=8090

# =========================================
# MS-COMENTARIOS
# =========================================
spring.cloud.gateway.server.webflux.routes[0].id=ms-comentarios
spring.cloud.gateway.server.webflux.routes[0].uri=http://localhost:8080
spring.cloud.gateway.server.webflux.routes[0].predicates[0]=Path=/comentarios/**

# =========================================
# MS-PROPIEDADES
# =========================================
spring.cloud.gateway.server.webflux.routes[1].id=ms-propiedades
spring.cloud.gateway.server.webflux.routes[1].uri=http://localhost:8081
spring.cloud.gateway.server.webflux.routes[1].predicates[0]=Path=/propiedades/**

# =========================================
# MS-ANFITRIONES
# =========================================
spring.cloud.gateway.server.webflux.routes[2].id=ms-anfitriones
spring.cloud.gateway.server.webflux.routes[2].uri=http://localhost:8082
spring.cloud.gateway.server.webflux.routes[2].predicates[0]=Path=/anfitriones/**

# =========================================
# MS-INQUILINOS
# =========================================
spring.cloud.gateway.server.webflux.routes[3].id=ms-inquilinos
spring.cloud.gateway.server.webflux.routes[3].uri=http://localhost:8083
spring.cloud.gateway.server.webflux.routes[3].predicates[0]=Path=/inquilinos/**

# =========================================
# MS-RESERVAS
# =========================================
spring.cloud.gateway.server.webflux.routes[4].id=ms-reservas
spring.cloud.gateway.server.webflux.routes[4].uri=http://localhost:8084
spring.cloud.gateway.server.webflux.routes[4].predicates[0]=Path=/reservas/**

# =========================================
# MS-PAGOS
# =========================================
spring.cloud.gateway.server.webflux.routes[5].id=ms-pagos
spring.cloud.gateway.server.webflux.routes[5].uri=http://localhost:8085
spring.cloud.gateway.server.webflux.routes[5].predicates[0]=Path=/pagos/**

# =========================================
# MS-LIMPIEZA
# =========================================
spring.cloud.gateway.server.webflux.routes[6].id=ms-limpieza
spring.cloud.gateway.server.webflux.routes[6].uri=http://localhost:8086
spring.cloud.gateway.server.webflux.routes[6].predicates[0]=Path=/limpieza/**

# =========================================
# MS-MENSAJERIA
# =========================================
spring.cloud.gateway.server.webflux.routes[7].id=ms-mensajeria
spring.cloud.gateway.server.webflux.routes[7].uri=http://localhost:8087
spring.cloud.gateway.server.webflux.routes[7].predicates[0]=Path=/mensajeria/**

# =========================================
# MS-PRECIOS
# =========================================
spring.cloud.gateway.server.webflux.routes[8].id=ms-precios
spring.cloud.gateway.server.webflux.routes[8].uri=http://localhost:8088
spring.cloud.gateway.server.webflux.routes[8].predicates[0]=Path=/precios/**

# =========================================
# MS-SEGUROS
# =========================================
spring.cloud.gateway.server.webflux.routes[9].id=ms-seguros
spring.cloud.gateway.server.webflux.routes[9].uri=http://localhost:8089
spring.cloud.gateway.server.webflux.routes[9].predicates[0]=Path=/seguros/**